/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apps;

/**
 *
 * @author ahmad luqman hakim
 */
public class lingkaran extends javax.swing.JFrame {

    /**
     * Creates new form lingkaran
     */
    public lingkaran() {
        initComponents();
        Rreset();
    }
    void Rreset (){
xjari.setText("");
qluas.setText(null);
qkeliling.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        xjari = new javax.swing.JTextField();
        qluas = new javax.swing.JLabel();
        qkeliling = new javax.swing.JLabel();
        Rruniung = new javax.swing.JButton();
        Rreset = new javax.swing.JButton();
        Rback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("lingkaran");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("jari-jari");

        xjari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xjariActionPerformed(evt);
            }
        });

        qluas.setText("luas");

        qkeliling.setText("keliling L");

        Rruniung.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmad luqman hakim\\Downloads\\next (1).png")); // NOI18N
        Rruniung.setText("runing");
        Rruniung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RruniungActionPerformed(evt);
            }
        });

        Rreset.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmad luqman hakim\\Downloads\\arrow.png")); // NOI18N
        Rreset.setText("reset");
        Rreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RresetActionPerformed(evt);
            }
        });

        Rback.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmad luqman hakim\\Downloads\\previous (1).png")); // NOI18N
        Rback.setText("back");
        Rback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qluas)
                                    .addComponent(qkeliling)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xjari, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(Rruniung)
                        .addGap(18, 18, 18)
                        .addComponent(Rreset)
                        .addGap(18, 18, 18)
                        .addComponent(Rback)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(xjari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rruniung)
                            .addComponent(Rreset)
                            .addComponent(Rback))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(qluas)
                .addGap(28, 28, 28)
                .addComponent(qkeliling)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xjariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xjariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xjariActionPerformed

    private void RruniungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RruniungActionPerformed
        // TODO add your handling code here:
        int jarijari = Integer.parseInt(xjari.getText());
        final double phi =3.14;
        double luas = phi*jarijari*jarijari;
        double keliling = 2*phi*jarijari;
        // Display the result in xkeliling text field
         qluas.setText("luas ="+luas);
         qkeliling.setText("keliling="+keliling);
    }//GEN-LAST:event_RruniungActionPerformed

    private void RbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbackActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_RbackActionPerformed

    private void RresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RresetActionPerformed
        // TODO add your handling code here:
        Rreset();
    }//GEN-LAST:event_RresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lingkaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lingkaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lingkaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lingkaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lingkaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Rback;
    private javax.swing.JButton Rreset;
    private javax.swing.JButton Rruniung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel qkeliling;
    private javax.swing.JLabel qluas;
    private javax.swing.JTextField xjari;
    // End of variables declaration//GEN-END:variables
}
