/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apps;

/**
 *
 * @author ahmad luqman hakim
 */
public class persegi extends javax.swing.JFrame {

    /**
     * Creates new form persegi
     */
    public persegi() {
        initComponents();
        Rreset();
    }
    void Rreset (){
    Tsisi.setText("");
    Tluas.setText(null);
    Tkeliling.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tsisi = new javax.swing.JTextField();
        Rback = new javax.swing.JButton();
        Rreset = new javax.swing.JButton();
        Rruning = new javax.swing.JButton();
        Tluas = new javax.swing.JLabel();
        Tkeliling = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("persegi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Sisi");

        Tsisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TsisiActionPerformed(evt);
            }
        });

        Rback.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmad luqman hakim\\Downloads\\previous (1).png")); // NOI18N
        Rback.setText("back");
        Rback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbackActionPerformed(evt);
            }
        });

        Rreset.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmad luqman hakim\\Downloads\\arrow.png")); // NOI18N
        Rreset.setText("reset");
        Rreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RresetActionPerformed(evt);
            }
        });

        Rruning.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmad luqman hakim\\Downloads\\next (1).png")); // NOI18N
        Rruning.setText("runing");
        Rruning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RruningActionPerformed(evt);
            }
        });

        Tluas.setText("luas");

        Tkeliling.setText("keliling");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tluas)
                            .addComponent(Tkeliling)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(57, 57, 57)
                                .addComponent(Tsisi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(Rruning)
                        .addGap(51, 51, 51)
                        .addComponent(Rreset)
                        .addGap(39, 39, 39)
                        .addComponent(Rback)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Tsisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rback)
                    .addComponent(Rreset)
                    .addComponent(Rruning))
                .addGap(48, 48, 48)
                .addComponent(Tluas)
                .addGap(38, 38, 38)
                .addComponent(Tkeliling)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TsisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TsisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TsisiActionPerformed

    private void RresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RresetActionPerformed
        // TODO add your handling code here:
        Rreset();
    }//GEN-LAST:event_RresetActionPerformed

    private void RbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbackActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_RbackActionPerformed

    private void RruningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RruningActionPerformed
        // TODO add your handling code here:
        int sisi = Integer.parseInt(Tsisi.getText());
        int luas = sisi*sisi;
        int keliling = 4*sisi;
        Tluas.setText("luas=" +luas);
        Tkeliling.setText("keliling=" +keliling);
        
    }//GEN-LAST:event_RruningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(persegi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(persegi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(persegi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(persegi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new persegi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Rback;
    private javax.swing.JButton Rreset;
    private javax.swing.JButton Rruning;
    private javax.swing.JLabel Tkeliling;
    private javax.swing.JLabel Tluas;
    private javax.swing.JTextField Tsisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
